#
# Test that the package can be installed using legacy method: `python setup.py install`
#

name: setup.py

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build-install-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest ]
        python: [ "3.5", "3.6", "3.7", "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade setuptools>=42 setuptools_scm numpy Cython
      - name: Build and install eigency
        run: |
          python setup.py build
          python setup.py install
      - name: Test eigency
        run: |
          cd tests
          python setup.py build
          python setup.py install
          mkdir test_run
          cp run_tests.py test_run/.
          cd test_run
          python run_tests.py
