#
# Test that the package can be installed using legacy method: `python setup.py install`
#

name: Build and test with setup.py

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  setup:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: [ "2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build dependencies
        run: |
          python -m pip install numpy Cython
      - name: Build and install eigency
        run: |
          python setup.py build
          python setup.py install
      - name: Test eigency
        run: |
          cd tests
          python setup.py build
          python setup.py install
          python run_tests.py
