#
# Test that the package can be built using standard pip wheel command: `python -m pip wheel .`
# https://pip.pypa.io/en/stable/cli/pip_wheel/
#

name: pip wheel

on:
#  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest ]
        python: [ "3.5", "3.6", "3.7", "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build dependencies
        run: |
          python -m pip install wheel
      - name: Build eigency
        run: |
          python -m pip wheel .
